// This file is generated by Slice Machine. Update with care!

import Images from './Images';
import Jobs from './Jobs';

export {
	Images,
	Jobs,
};

export const components = {
	images: Images,
	jobs: Jobs,
};
