// This file is generated by Slice Machine. Update with care!

import Images from './Images';
import Jobs from './Jobs';
import Machine from './Machine';
import Staff from './Staff';

export {
	Images,
	Jobs,
	Machine,
	Staff,
};

export const components = {
	images: Images,
	jobs: Jobs,
	machine: Machine,
	staff: Staff,
};
