// This file is generated by Slice Machine. Update with care!

import Feedback from './Feedback';
import Images from './Images';
import Jobs from './Jobs';
import Machine from './Machine';
import NavigationLinks from './NavigationLinks';
import Staff from './Staff';
import Values from './Values';

export {
	Feedback,
	Images,
	Jobs,
	Machine,
	NavigationLinks,
	Staff,
	Values,
};

export const components = {
	feedback: Feedback,
	images: Images,
	jobs: Jobs,
	machine: Machine,
	navigation_links: NavigationLinks,
	staff: Staff,
	values: Values,
};
