export default function Colors() {
  const COLORS_1 = {
    background: "#F8F7F3",
    navigation: {
      logo: "/images/logo/logo2.png",
      bgTexture: "/images/background/navBg1.png",
      bg: "#04132A",
      color: "white",
      colorHover: "orange",
      bgHover: "#072146",
      subBg: "#04132A",
      subColor: "white",
      subBgHover: "#072146",
      subIcon: "orange",
      hamburgerIcon: "white",
      hamburgerIconBg: "#072147",
      selectColors: { color: "white", bg: "#04132A" },
      selectLanguage: { color: "white", bg: "#04132A" },
    },
    footer: {
      logo: "/images/logo/logo2.png",
      bgTexture: "/images/background/navBg1.png",
      bg: "#04132A",
      color: "white",
      colorHover: "orange",
    },

    career: {
      color: "black",
      bg: "",
      colorExpanded: "black",
      bgExpanded: "gray.200",
      button: {
        color: "black",
        bg: "",
        colorHover: "black",
        bgHover: "#E4E5E7",
        colorExpanded: "white",
        bgExpanded: "#072248",
      },
    },
    contacts: {
      card: {
        bgTop: "#08254F",
        bgBot: "White",
        color: "#1A202C",
        bgTopTexture: "/images/background/aboutBg.png",
        border: "072248",
      },
      form: { color: "black", bg: "white", colorIcon: "black" },
      button: { bg: "#072155", color: "white", colorHover: "orange" },
      bg: "#08254F",
      bgTexture: "/images/background/aboutBg.png",
      color: "white",
      colorIcon: "#1970F1",
    },
    gallery: { bg: "#041126", bgTexture: "/images/background/galleryBg.png" },
    home: {
      bgImage: "/images/background/main1a.jpg",
      image: "/images/home/whyUs.jpg",
      color: "white",
      colorLink: "orange",
      bg: "",
      whyUs: { color: "black", bg: "" },
      aboutUs: {
        image: "/images/home/aboutUs.jpg",
        color: "white",
        bg: "#08254F",
        bgTexture: "/images/background/aboutBg.png",
      },
      feedback: { color: "black", bg: "" },
      values: { color: "black", bg: "white" },
    },
    turning: {
      image: "/images/turning/t5.jpg",
      bgTexture: "/images/background/aboutBg.png",
      bgBot: "#08254F",
      bgTop: "",
      colorTop: "black",
      colorBot: "white",
    },
    milling: {
      image: "/images/milling/m1.jpg",
      bgTexture: "/images/background/aboutBg.png",
      bgBot: "#08254F",
      bgTop: "",
      colorTop: "black",
      colorBot: "white",
    },
    design: { image: "/images/design/d1.jpg", color: "black", bg: "" },
    general: { color: "black", bg: "" },
    privacy: { color: "black", bg: "" },
  };
  return COLORS_1;
}
